### ISSUE TITLE
Can't find a Behaving version that works on Python 3.9

### ISSUE THREAD

**Issue by ThrawnCA** [ggozad/behaving#133]
We're trying to run file upload tests on Python 3.9, which means we need to use Selenium 4 in order to fix https://github.com/SeleniumHQ/selenium/issues/8762, but there doesn't seem to be any Behaving version that we can use.

- Behaving 2.0.0 is incompatible with Selenium 4; attempting to click on an element with steps like 'I click the link with text that contains "{text}"' results in an `AttributeError: 'dict' object has no attribute 'click'`
- Behaving 3.0.0 to 3.0.4 requires Splinter 0.16.0, which is incompatible with Selenium 4 (won't install).
- Behaving 3.0.5+ requires Python 3.10.

**Comment by ggozad** [comment]
Will try to find some time and merge the stuff that I have pending while requiring python 3.9.

**Comment by ggozad** [comment]
This should be working now with 3.1.4.
